### ISSUE TITLE
Issue on toggling on this package

### ISSUE THREAD

**Issue by lee-liu** [olafklingt/fold-whatever#13]
Hi, I've installed this fold-whatever package, but it did not seem to work when I clicked the Fold All. Is there anything I missed? Thanks for help, I think this package will be very useful to me.

**Comment by olafklingt** [comment]
Did you setup a regular expression that matches with what you want to fold?

**Comment by lee-liu** [comment]
Oh, thanks for reminder, I though the default regex will cover <...>. I've reset it and it works now. By the way, is it possible to toggle only a specific regex match at one time? i.e. if I have {...}, [...], and <...> in my code, and I only want to fold all the {...}?

**Comment by olafklingt** [comment]
This is a feature i thought about but havnt implemented it. Could do so but not during the next week

**Comment by olafklingt** [comment]
just published a update that implements folding of specific regexes #9
