### ISSUE TITLE
Doesn't match folds over multiple lines

### ISSUE THREAD

**Issue by Sod-Almighty** [olafklingt/fold-whatever#2]
This is just ridiculous. Consider the following regex:
```
/(\{)(.*?)(\})/
```
The following code will be folded:
```
{ test }
```
The following code will NOT be folded:
```
{
test
}
```
What's the point!?

Also, while we're on the subject, if you're gonna extend the folding system, at least make it compatible with the built-in folding. Let us toggle _both_ types of folding at once, not separately.

**Comment by olafklingt** [comment]
Usually standard regexes are not over multiple lines.
Right now I don't know how to solve this.

> What's the point!?

you mean point or problem?

> Also, while we're on the subject, if you're gonna extend the folding system, at least make it compatible with the built-in folding. Let us toggle both types of folding at once, not separately.

What behavior do you expect?

**Comment by Sod-Almighty** [comment]
> you mean point or problem?

I mean point. What _possible_ use can anyone have for the ability to fold _single lines_? The entire purpose of folding is to reduce many lines into one. If your extension doesn't do this, then why write it?

> What behavior do you expect?

I expect that when I tell Atom to fold or unfold regions, it should treat your extension's regions no differently to its own. Why would I want one hotkey to collapse _standard_ regions, and another hotkey to collapse _your_ regions?

**Comment by olafklingt** [comment]
Why would I like to answer your rhetorical questions?
Please mind your words.

**Comment by olafklingt** [comment]
#3
