### ISSUE TITLE
matches over multiple lines do not fold the desired range but too much

### ISSUE THREAD

**Issue by olafklingt** [olafklingt/fold-whatever#3]
/(\{)([.\n]*?)(\})/

```
folding after this {
 test
 } this should be visible
and not only this
```

folds into 

```
folding after this {
and not only this
```

and not

```
folding after this {} this should be visible
and not only this
```

as expected ...

**Comment by Sod-Almighty** [comment]
Right, because my BUG REPORT that FAILING TO FOLD MORE THAN ONE LINE makes this extension COMPLETELY GODDAMN USELESS wasn't worth ADDRESSING. Apparently minding my words was FAR more important.

**Comment by olafklingt** [comment]
this was a false alarm because some other activated folding happen not the one defined in fold-whatever

multiline folding can be done for example like this
/(\<\!--)(.|\s)+?(--\>)/g
for html style comments over multiple lines. where the surrounding arrows are still visible.
