### ISSUE TITLE
Autofolding

### ISSUE THREAD

**Issue by saivan** [olafklingt/fold-whatever#4]
How difficult do you think it would be to autofold anything that matches a particular pattern. I had something like markdown in mind. If you typed out:

```md
![some-really-long-thing](with some really long alt text)
```

It would be cool to turn this into:

```md
![{...}]({...})
```

Or even:

```md
![{...})
```

If the user gets to within two characters of the fold, it will automatically unfold.

**Comment by olafklingt** [comment]
On May 2, 2018 1:50:26 PM GMT+08:00, saivan <notifications@github.com> wrote:
>How difficult do you think it would be to autofold anything that
>matches a particular pattern. I had something like markdown in mind. If
>you typed out:
>
>```md
>![some-really-long-thing](with some really long alt text)
>```
>
>It would be cool to turn this into:
>
>```md
>![{...}]({...})
>```
>
>Or even:
>
>```md
>![{...})
>```

The second style is allready possible. 


>
>If the user gets to within two characters of the fold, it will
>automatically unfold.

This is not the typical way how folds are usually treated in atom, so I don't really know how this could be done. 

I personally i also don't think it would be that helpful. 



-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by saivan** [comment]
When you say the second style is possible, could you elaborate more?

**Comment by saivan** [comment]
Okay, I figured it out. But it seems that if I have more than one match on a single line, it will only fold the last one.

**Comment by olafklingt** [comment]
I guess this depends on your regex or the command you use to do the folding. but i can only guess

**Comment by saivan** [comment]
Oh I see, So its supposed to be able to match more than once per line.
Thanks for the awesome plugin :) I'll go ahead and close this then.

**Comment by olafklingt** [comment]
> Oh I see, So its supposed to be able to match more than once per line.

yes. The two default regexes might help you to find the right way to design the right regex for your case.
actually to fold md-links would be interesting for me too. so when you found one which works just post it.

> Thanks for the awesome plugin :) I'll go ahead and close this then.

thanks.

**Comment by saivan** [comment]
I mean you could just use a combination of this to get the first match

```
(\[)(.+?)(\]\(.*?\))
```

And:

```
(\[.+?\]\()(.*?)(\))
```

to get the second match
